
export const ACTIONS = {
    OPEN_LOGIN_MODAL: 'OPEN_LOGIN_MODAL',
    OPEN_REGISTER_MODAL: 'OPEN_REGISTER_MODAL',
    CLOSE_LOGIN_MODAL: 'CLOSE_LOGIN_MODAL',
    CLOSE_REGISTER_MODAL: 'CLOSE_REGISTER_MODAL',
    OPEN_QUIZ_MODAL: 'OPEN_QUIZ_MODAL',
    CLOSE_QUIZ_MODAL: 'CLOSE_QUIZ_MODAL',
    ADD_QUIZ: 'ADD_QUIZ',
    EDIT_QUESTION: 'EDIT_QUESTION',
    INITIAL_QUESTION: 'INITIAL_QUESTION',
    EDIT_CHOICE: 'EDIT_CHOICE',
    CHOICE_BUTTON: 'CHOICE_BUTTON'
}